version: '3.4'

services:
  db:
    image: mysql:8.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: crmwithspringboot
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - crm-network
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crmwithspringboot?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - crm-network
networks:
  crm-network:
    driver: bridge