version: '3.4'

services:
  db:
    image: mysql:8.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: crmwithspringboot
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - crm-network

  app:
    image: jvzalves/crm-with-spring-boot
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crmwithspringboot?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - crm-network
    command: java -jar app.jar   

networks:
  crm-network:
    driver: bridge
