name: Continuous Integration and Delivery With Github Actions

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application .jar with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image with correct tag
        run: docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/crm-with-spring-boot:latest

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/crm-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/crm-with-spring-boot:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/crm-with-spring-boot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/crm-with-spring-boot:${{ github.run_id }}
